### ISSUE TITLE
Add `preserve` option

### ISSUE THREAD

**Issue by Antonio-Laguna** [polemius/postcss-clamp#11]
Hi @polemius !

After picking up development on postcss-preset-env I came across this issue: https://github.com/csstools/postcss-plugins/issues/114 and would love to add this plugin there. However to keep it consistent with other plugins we'd like to add `preserve` to keep both options. Is this something you would consider adding to the plugin or accepting a PR that adds this?

Using the same example but with `preserve: true` as an option:

```css
.foo {
  width: clamp(10px, 4em, 80px);
}

/* Will become */

.foo {
  width: clamp(10px, 4em, 80px);
  width: max(10px, min(4em, 80px));
}
```
